export const GET_FORECAST_WEATHER = 'GET_FORECAST_WEATHER';
export const GET_FORECAST_WEATHER_SUCCESS = 'GET_FORECAST_WEATHER_SUCCESS';

export const OPEN_SECTION = 'OPEN_SECTION';
export const CLOSE_SECTION = 'CLOSE_SECTION';
export const INITIAL_CITY = 'London';
